// Seed data — all rules, document types, and case types loaded in-memory for serverless

export const documentTypes = [
    { id: 1, code: "DOC_BUSINESS_REGISTRATION", name: "사업자등록증", category: "BASIC", enabled: true },
    { id: 2, code: "DOC_CORPORATE_REGISTRY", name: "법인 등기사항전부증명서", category: "BASIC", enabled: true },
    { id: 3, code: "DOC_ACCOUNT_OPENING_FORM", name: "계좌개설 신청서", category: "BASIC", enabled: true },
    { id: 4, code: "DOC_CUSTOMER_DUE_DILIGENCE_FORM", name: "고객확인서(법인 기본정보서)", category: "BASIC", enabled: true },
    { id: 5, code: "DOC_REPRESENTATIVE_ID", name: "대표자 실명확인증표(신분증)", category: "BASIC", enabled: true },
    { id: 6, code: "DOC_CORPORATE_SEAL_OR_SIGNATURE", name: "거래 인감/서명 정보", category: "BASIC", enabled: true },
    { id: 7, code: "DOC_CONTACT_INFO_VERIFICATION", name: "연락처/주소 확인 자료", category: "BASIC", enabled: true },
    { id: 8, code: "DOC_PROXY_ID", name: "대리인 신분증", category: "PROXY_AUTH", enabled: true },
    { id: 9, code: "DOC_POWER_OF_ATTORNEY", name: "위임장", category: "PROXY_AUTH", enabled: true },
    { id: 10, code: "DOC_CORPORATE_SEAL_CERTIFICATE", name: "법인 인감증명서", category: "PROXY_AUTH", enabled: true },
    { id: 11, code: "DOC_USE_OF_SEAL_FORM", name: "사용인감계", category: "PROXY_AUTH", enabled: true },
    { id: 12, code: "DOC_EMPLOYMENT_CERTIFICATE", name: "재직증명서", category: "PROXY_AUTH", enabled: true },
    { id: 13, code: "DOC_AUTHORIZATION_PROOF", name: "대리권/권한 확인 서류", category: "PROXY_AUTH", enabled: true },
    { id: 14, code: "DOC_BOARD_RESOLUTION", name: "이사회 의사록/결의서", category: "PROXY_AUTH", enabled: true },
    { id: 15, code: "DOC_JOINT_REP_AUTH_PROOF", name: "공동대표 권한 행사 확인서류", category: "PROXY_AUTH", enabled: true },
    { id: 16, code: "DOC_SHAREHOLDER_REGISTER", name: "주주명부", category: "UBO_GOVERNANCE", enabled: true },
    { id: 17, code: "DOC_MEMBER_REGISTER", name: "사원명부/출자자명부", category: "UBO_GOVERNANCE", enabled: true },
    { id: 18, code: "DOC_BENEFICIAL_OWNER_DECLARATION", name: "실제소유자 확인서/신고서", category: "UBO_GOVERNANCE", enabled: true },
    { id: 19, code: "DOC_OWNERSHIP_STRUCTURE_CHART", name: "지배구조도", category: "UBO_GOVERNANCE", enabled: true },
    { id: 20, code: "DOC_ARTICLES_OF_INCORPORATION", name: "정관", category: "UBO_GOVERNANCE", enabled: true },
    { id: 21, code: "DOC_BYLAWS_OR_RULES", name: "규약/회칙", category: "UBO_GOVERNANCE", enabled: true },
    { id: 22, code: "DOC_CONTROL_PERSON_EXPLANATION", name: "사실상 지배자 소명자료", category: "UBO_GOVERNANCE", enabled: true },
    { id: 23, code: "DOC_TRANSACTION_PURPOSE_FORM", name: "금융거래 목적 확인서", category: "TRANSACTION", enabled: true },
    { id: 24, code: "DOC_SOURCE_OF_FUNDS_EXPLANATION", name: "자금원천 설명서", category: "TRANSACTION", enabled: true },
    { id: 25, code: "DOC_FINANCIAL_STATEMENT", name: "재무제표", category: "TRANSACTION", enabled: true },
    { id: 26, code: "DOC_TAX_INVOICE_OR_CONTRACT", name: "세금계산서/거래계약서", category: "TRANSACTION", enabled: true },
    { id: 27, code: "DOC_OFFICE_LEASE", name: "사업장 임대차계약서", category: "TRANSACTION", enabled: true },
    { id: 28, code: "DOC_BUSINESS_WEBSITE_OR_PHOTO", name: "홈페이지/간판/사업장 사진", category: "TRANSACTION", enabled: true },
    { id: 29, code: "DOC_STARTUP_SUPPORT_PROOF", name: "창업지원기관 확인자료", category: "TRANSACTION", enabled: true },
    { id: 30, code: "DOC_FOREIGN_INCORPORATION_CERT", name: "외국법인 설립 증빙", category: "FOREIGN", enabled: true },
    { id: 31, code: "DOC_FOREIGN_REGISTRY_EXTRACT", name: "외국 등기/등록 증빙", category: "FOREIGN", enabled: true },
    { id: 32, code: "DOC_NOTARIZATION_OR_APOSTILLE", name: "공증/아포스티유/영사확인", category: "FOREIGN", enabled: true },
    { id: 33, code: "DOC_PASSPORT_OR_FOREIGN_ID", name: "외국 대표자/대리인 신분증(여권)", category: "FOREIGN", enabled: true },
    { id: 34, code: "DOC_KOREAN_TRANSLATION", name: "번역문", category: "FOREIGN", enabled: true },
    { id: 35, code: "DOC_TAX_RESIDENCY_FORM", name: "세무거주지/FATCA/CRS 관련 문서", category: "FOREIGN", enabled: true },
    { id: 36, code: "DOC_FOREIGN_SECURITIES_AGREEMENT", name: "해외상품 약정서", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 37, code: "DOC_DERIVATIVES_RISK_DISCLOSURE", name: "파생상품 위험고지서", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 38, code: "DOC_PRODUCT_SUITABILITY_FORM", name: "투자자 적합성 확인서", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 39, code: "DOC_TRADING_AUTHORITY_FORM", name: "매매거래 권한 확인서", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 40, code: "DOC_CMA_ADDITIONAL_TERMS", name: "CMA 추가 약관 동의서", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 41, code: "DOC_OTHER_PRODUCT_SPECIFIC_FORM", name: "기타 상품별 추가 양식", category: "PRODUCT_SPECIFIC", enabled: true },
    { id: 42, code: "DOC_EXCEPTION_REVIEW_MEMO", name: "예외심사 메모", category: "EXCEPTION", enabled: true },
    { id: 43, code: "DOC_COMPLIANCE_APPROVAL", name: "준법감시 승인서", category: "EXCEPTION", enabled: true },
    { id: 44, code: "DOC_AML_REVIEW_NOTE", name: "AML 심사 기록", category: "EXCEPTION", enabled: true },
    { id: 45, code: "DOC_REJECTION_REASON_RECORD", name: "반려 사유 기록", category: "EXCEPTION", enabled: true },
];

export const caseTypes = [
    { id: 1, code: "C01", name: "국내 영리법인 + 대표자 본인 + 일반계좌", description: "대표자 본인 내점, 실제소유자 확인 가능, 고위험 아님" },
    { id: 2, code: "C02", name: "국내 영리법인 + 임직원 대리", description: "법인 소속 임직원 대리 내점" },
    { id: 3, code: "C03", name: "국내 영리법인 + 외부 대리인", description: "외부 대리인/수임인 내점" },
    { id: 4, code: "C04", name: "공동대표 + 단독 가능", description: "공동대표 중 단독 대표권 행사 가능" },
    { id: 5, code: "C05", name: "공동대표 + 공동행사 필요", description: "공동대표 전원 공동행사 필요" },
    { id: 6, code: "C06", name: "비영리법인 + 대표자 본인", description: "국내 비영리법인, 대표자 본인 내점" },
    { id: 7, code: "C07", name: "비영리법인 + 대리인", description: "국내 비영리법인, 대리인 내점" },
    { id: 8, code: "C08", name: "법인격 없는 단체/임의단체", description: "대표자 또는 관리책임자 신청" },
    { id: 9, code: "C09", name: "외국법인", description: "국내 지점/사무소 포함, 기본 승인필요" },
    { id: 10, code: "C10", name: "신설법인", description: "사업 개시 초기, 일반 사업실적 부족" },
    { id: 11, code: "C11", name: "실제소유자 확인 곤란", description: "다단계 지배구조 또는 복잡한 지분구조" },
    { id: 12, code: "C12", name: "고위험 플래그", description: "해외/고위험 국가/특수심사 필요" },
    { id: 13, code: "C13", name: "상품 추가", description: "해외주식/외화, 파생, 채권 등 부가 상품" },
    { id: 14, code: "C14", name: "비대면 사전접수", description: "비대면 사전접수 후 대면 확인 예정" },
];

export const rules = [
    { id: 1, rule_name: "C01 기본서류 - 국내 영리법인 대표자 본인", priority: 10, enabled: true, conditions: { all: [{ field: "customer_type", eq: "FOR_PROFIT_CORP_DOMESTIC" }, { field: "applicant_type", eq: "REPRESENTATIVE_SELF" }, { field: "account_type", eq: "BROKERAGE_GENERAL" }] }, required_documents: ["DOC_BUSINESS_REGISTRATION", "DOC_CORPORATE_REGISTRY", "DOC_REPRESENTATIVE_ID", "DOC_ACCOUNT_OPENING_FORM", "DOC_CUSTOMER_DUE_DILIGENCE_FORM", "DOC_CORPORATE_SEAL_OR_SIGNATURE", "DOC_BENEFICIAL_OWNER_DECLARATION", "DOC_TRANSACTION_PURPOSE_FORM"], optional_documents: ["DOC_FINANCIAL_STATEMENT", "DOC_SOURCE_OF_FUNDS_EXPLANATION"], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "국내 영리법인 대표자 본인 내점 기본서류입니다." },
    { id: 2, rule_name: "C02 대리인 추가 - 임직원 대리", priority: 20, enabled: true, conditions: { all: [{ field: "applicant_type", eq: "INTERNAL_EMPLOYEE_PROXY" }] }, required_documents: ["DOC_PROXY_ID", "DOC_POWER_OF_ATTORNEY", "DOC_EMPLOYMENT_CERTIFICATE"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "임직원 대리 신청이므로 대리인 신분증, 위임장, 재직증명서가 필요합니다." },
    { id: 3, rule_name: "C02 인감 대체 그룹 - 임직원/외부 대리", priority: 21, enabled: true, conditions: { any: [{ field: "applicant_type", eq: "INTERNAL_EMPLOYEE_PROXY" }, { field: "applicant_type", eq: "EXTERNAL_PROXY" }] }, required_documents: ["DOC_CORPORATE_SEAL_CERTIFICATE"], optional_documents: ["DOC_USE_OF_SEAL_FORM"], blocked_if_missing: true, escalate_if_true: false, output_status: null, output_case_tags: [], explanation_template: "대리 신청 시 법인 인감증명서 또는 사용인감계가 필요합니다." },
    { id: 4, rule_name: "C03 외부 대리인 추가", priority: 25, enabled: true, conditions: { all: [{ field: "applicant_type", eq: "EXTERNAL_PROXY" }] }, required_documents: ["DOC_PROXY_ID", "DOC_POWER_OF_ATTORNEY", "DOC_AUTHORIZATION_PROOF", "DOC_BOARD_RESOLUTION"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "외부 대리인이므로 대리권 소명자료와 이사회 결의서가 필요합니다." },
    { id: 5, rule_name: "C04 공동대표 단독 행사", priority: 30, enabled: true, conditions: { all: [{ field: "applicant_type", eq: "JOINT_REP_SINGLE_ACTION_ALLOWED" }] }, required_documents: ["DOC_JOINT_REP_AUTH_PROOF"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "공동대표 단독행사 가능 여부 확인 서류가 필요합니다." },
    { id: 6, rule_name: "C05 공동대표 공동행사 필요", priority: 31, enabled: true, conditions: { all: [{ field: "applicant_type", eq: "JOINT_REP_JOINT_ACTION_REQUIRED" }] }, required_documents: ["DOC_JOINT_REP_AUTH_PROOF"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "공동대표 전원의 공동행사가 필요합니다. 전원 서명/날인 확인서류를 제출하세요." },
    { id: 7, rule_name: "C06/C07 비영리법인 추가서류", priority: 35, enabled: true, conditions: { all: [{ field: "customer_type", eq: "NON_PROFIT_CORP" }] }, required_documents: ["DOC_ARTICLES_OF_INCORPORATION", "DOC_BYLAWS_OR_RULES"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "비영리법인이므로 정관과 규약이 필요합니다." },
    { id: 8, rule_name: "C08 법인격 없는 단체", priority: 36, enabled: true, conditions: { all: [{ field: "customer_type", eq: "NON_CORPORATE_ORG" }] }, required_documents: ["DOC_BYLAWS_OR_RULES"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "법인격 없는 단체이므로 회칙/규약이 필요합니다." },
    { id: 9, rule_name: "C09 외국법인 추가서류", priority: 40, enabled: true, conditions: { any: [{ field: "customer_type", eq: "FOREIGN_CORP" }, { field: "customer_type", eq: "FOREIGN_ORG" }] }, required_documents: ["DOC_FOREIGN_INCORPORATION_CERT", "DOC_FOREIGN_REGISTRY_EXTRACT", "DOC_KOREAN_TRANSLATION", "DOC_NOTARIZATION_OR_APOSTILLE", "DOC_PASSPORT_OR_FOREIGN_ID", "DOC_TAX_RESIDENCY_FORM"], optional_documents: [], blocked_if_missing: true, escalate_if_true: true, output_status: "APPROVAL_PENDING", output_case_tags: [], explanation_template: "외국법인이므로 설립증빙, 번역문, 공증 서류가 필요하며 승인이 필요합니다." },
    { id: 10, rule_name: "C10 신설법인 추가서류", priority: 45, enabled: true, conditions: { all: [{ field: "is_new_corp", is_true: true }] }, required_documents: ["DOC_OFFICE_LEASE", "DOC_BUSINESS_WEBSITE_OR_PHOTO"], optional_documents: ["DOC_STARTUP_SUPPORT_PROOF"], blocked_if_missing: false, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "신설법인이므로 사업장 증빙(임대차계약서, 사업장 사진 등)이 필요합니다." },
    { id: 11, rule_name: "E01 사업자 상태 이상 - 휴업", priority: 1, enabled: true, conditions: { all: [{ field: "business_status", eq: "SUSPENDED" }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "BLOCKED", output_case_tags: [], explanation_template: "사업자 상태가 '휴업'이므로 접수가 차단됩니다." },
    { id: 12, rule_name: "E01 사업자 상태 이상 - 폐업", priority: 1, enabled: true, conditions: { all: [{ field: "business_status", eq: "CLOSED" }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "BLOCKED", output_case_tags: [], explanation_template: "사업자 상태가 '폐업'이므로 접수가 차단됩니다." },
    { id: 13, rule_name: "E01 사업자 상태 이상 - 확인불가", priority: 1, enabled: true, conditions: { all: [{ field: "business_status", eq: "UNKNOWN" }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "BLOCKED", output_case_tags: [], explanation_template: "사업자 상태를 확인할 수 없으므로 접수가 차단됩니다." },
    { id: 14, rule_name: "E02 서류 불일치", priority: 2, enabled: true, conditions: { all: [{ field: "risk_flags.document_mismatch", is_true: true }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "NEEDS_SUPPLEMENT", output_case_tags: [], explanation_template: "서류 간 정보 불일치가 감지되었습니다. 보완 후 재접수하세요." },
    { id: 15, rule_name: "E03 공동대표 권한 불명확", priority: 3, enabled: true, conditions: { all: [{ any: [{ field: "applicant_type", eq: "JOINT_REP_SINGLE_ACTION_ALLOWED" }, { field: "applicant_type", eq: "JOINT_REP_JOINT_ACTION_REQUIRED" }] }, { field: "risk_flags.proxy_authority_unclear", is_true: true }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "BLOCKED", output_case_tags: [], explanation_template: "공동대표 권한이 확인되지 않아 접수가 차단되었습니다." },
    { id: 16, rule_name: "E04 대리권 불명확 - 위임장 없음", priority: 3, enabled: true, conditions: { all: [{ any: [{ field: "applicant_type", eq: "INTERNAL_EMPLOYEE_PROXY" }, { field: "applicant_type", eq: "EXTERNAL_PROXY" }] }, { field: "risk_flags.proxy_authority_unclear", is_true: true }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "BLOCKED", output_case_tags: [], explanation_template: "대리인 신청이나 위임장/대리권 증빙이 불명확하여 접수가 차단됩니다." },
    { id: 17, rule_name: "E05 실제소유자 미확인", priority: 4, enabled: true, conditions: { all: [{ field: "ubo_confirmable", is_false: true }] }, required_documents: ["DOC_OWNERSHIP_STRUCTURE_CHART", "DOC_CONTROL_PERSON_EXPLANATION", "DOC_AML_REVIEW_NOTE"], optional_documents: [], blocked_if_missing: false, escalate_if_true: true, output_status: "ESCALATION_REQUIRED", output_case_tags: [], explanation_template: "실제소유자를 확인할 수 없어 추가 심사가 필요합니다." },
    { id: 18, rule_name: "E05 다단계 지배구조", priority: 4, enabled: true, conditions: { all: [{ field: "multi_layer_ownership", is_true: true }] }, required_documents: ["DOC_OWNERSHIP_STRUCTURE_CHART", "DOC_SHAREHOLDER_REGISTER"], optional_documents: [], blocked_if_missing: false, escalate_if_true: true, output_status: "ESCALATION_REQUIRED", output_case_tags: [], explanation_template: "다단계 지배구조로 인해 추가 심사가 필요합니다." },
    { id: 19, rule_name: "E06 신설법인 사업장 증빙 강화", priority: 5, enabled: true, conditions: { all: [{ field: "is_new_corp", is_true: true }] }, required_documents: ["DOC_OFFICE_LEASE", "DOC_BUSINESS_WEBSITE_OR_PHOTO"], optional_documents: ["DOC_STARTUP_SUPPORT_PROOF"], blocked_if_missing: false, escalate_if_true: false, output_status: "READY_FOR_REVIEW", output_case_tags: [], explanation_template: "신설법인이므로 사업실체 확인을 위해 사업장/홈페이지 증빙이 필요합니다." },
    { id: 20, rule_name: "E09 고위험 국가 관련", priority: 2, enabled: true, conditions: { all: [{ field: "risk_flags.high_risk_country", is_true: true }] }, required_documents: ["DOC_AML_REVIEW_NOTE", "DOC_COMPLIANCE_APPROVAL"], optional_documents: [], blocked_if_missing: true, escalate_if_true: true, output_status: "ESCALATION_REQUIRED", output_case_tags: [], explanation_template: "고위험 국가 관련 법인이므로 AML 심사 및 준법 승인이 필요합니다." },
    { id: 21, rule_name: "E09 PEP/제재 대상", priority: 2, enabled: true, conditions: { all: [{ field: "risk_flags.pep_sanction", is_true: true }] }, required_documents: ["DOC_AML_REVIEW_NOTE", "DOC_COMPLIANCE_APPROVAL"], optional_documents: [], blocked_if_missing: true, escalate_if_true: true, output_status: "ESCALATION_REQUIRED", output_case_tags: [], explanation_template: "PEP/제재 대상 관련이므로 강화 심사가 필요합니다." },
    { id: 22, rule_name: "E10 해외상품 추가서류", priority: 50, enabled: true, conditions: { all: [{ field: "account_type", eq: "FOREIGN_SECURITIES" }] }, required_documents: ["DOC_FOREIGN_SECURITIES_AGREEMENT"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: null, output_case_tags: [], explanation_template: "해외주식/외화 상품 신청이므로 해외상품 약정서가 필요합니다." },
    { id: 23, rule_name: "E10 파생상품 추가서류", priority: 50, enabled: true, conditions: { all: [{ field: "account_type", eq: "DERIVATIVES" }] }, required_documents: ["DOC_DERIVATIVES_RISK_DISCLOSURE", "DOC_PRODUCT_SUITABILITY_FORM"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: null, output_case_tags: [], explanation_template: "파생상품 신청이므로 위험고지서와 적합성 확인서가 필요합니다." },
    { id: 24, rule_name: "E10 CMA 추가서류", priority: 50, enabled: true, conditions: { all: [{ field: "account_type", eq: "CMA_SETTLEMENT" }] }, required_documents: ["DOC_CMA_ADDITIONAL_TERMS"], optional_documents: [], blocked_if_missing: true, escalate_if_true: false, output_status: null, output_case_tags: [], explanation_template: "CMA/입출금성 계좌이므로 CMA 추가 약관 동의가 필요합니다." },
    { id: 25, rule_name: "최종 지배자 불명", priority: 4, enabled: true, conditions: { all: [{ field: "ultimate_owner_unknown", is_true: true }] }, required_documents: ["DOC_CONTROL_PERSON_EXPLANATION", "DOC_AML_REVIEW_NOTE"], optional_documents: [], blocked_if_missing: false, escalate_if_true: true, output_status: "ESCALATION_REQUIRED", output_case_tags: [], explanation_template: "최종 지배자를 특정할 수 없어 추가 심사가 필요합니다." },
    { id: 26, rule_name: "C14 비대면 사전접수", priority: 55, enabled: true, conditions: { all: [{ field: "applicant_type", eq: "NON_FACE_TO_FACE_REQUEST" }] }, required_documents: [], optional_documents: [], blocked_if_missing: false, escalate_if_true: false, output_status: "APPROVAL_PENDING", output_case_tags: [], explanation_template: "비대면 사전접수입니다. 최종 개설은 대면 검증 완료 후에만 허용됩니다." },
];
